version: '3.8'  # Docker Compose 버전

services:
  web:
    build:
      context: .  # 현재 디렉토리에서 Dockerfile을 기준으로 빌드
    ports:
      - "3010:3010"  # 외부 3000 포트를 컨테이너 내부의 3000 포트에 연결
    environment:
      - NODE_ENV=production  # 환경 변수 설정 (production 모드로 설정)
    volumes:
      - .:/app  # 현재 디렉토리를 컨테이너의 /app 디렉토리로 마운트 (개발 환경에서 유용)
    networks:
      - app-network  # 네트워크 연결

  # 필요한 경우, 데이터베이스 서비스도 추가할 수 있습니다.
  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - app-network

networks:
  app-network:  # 네트워크 정의
    driver: bridge  # 브릿지 네트워크 사용

# volumes:
#   db_data: {}  # 데이터베이스 데이터를 저장할 볼륨 (필요시 주석을 해제)
